// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void AlarmIconBouncing_Animation( lv_obj_t *TargetObject, int delay);
void WeatherRefreshNotice_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_ClockPage
void ui_ClockPage_screen_init(void);
lv_obj_t *ui_ClockPage;
lv_obj_t *ui_TimeBlock;
lv_obj_t *ui_DateLabel;
void ui_event_GoMenu( lv_event_t * e);
lv_obj_t *ui_GoMenu;
lv_obj_t *ui_TimeBlock12H;
lv_obj_t *ui_LabelFor12H;
// CUSTOM VARIABLES

// SCREEN: ui_MenuPage
void ui_MenuPage_screen_init(void);
lv_obj_t *ui_MenuPage;
lv_obj_t *ui_TheBar;
void ui_event_BackToClockBottom( lv_event_t * e);
lv_obj_t *ui_BackToClockBottom;
lv_obj_t *ui_Disconnected;
lv_obj_t *ui_Connected;
lv_obj_t *ui_BarLabel;
void ui_event_SettingsIcon( lv_event_t * e);
lv_obj_t *ui_SettingsIcon;
lv_obj_t *ui_SettingsLabel;
void ui_event_CalendarIcon( lv_event_t * e);
lv_obj_t *ui_CalendarIcon;
lv_obj_t *ui_CalendarLabel;
void ui_event_AlarmIcon( lv_event_t * e);
lv_obj_t *ui_AlarmIcon;
lv_obj_t *ui_AlarmLabel;
void ui_event_WeatherIcon( lv_event_t * e);
lv_obj_t *ui_WeatherIcon;
lv_obj_t *ui_WeatherLabel;
void ui_event_HumidityIcon( lv_event_t * e);
lv_obj_t *ui_HumidityIcon;
lv_obj_t *ui_HumidityLabel;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsPage
void ui_SettingsPage_screen_init(void);
lv_obj_t *ui_SettingsPage;
lv_obj_t *ui_CalendarSettings1;
void ui_event_CalendarDropdown1( lv_event_t * e);
lv_obj_t *ui_CalendarDropdown1;
lv_obj_t *ui_TimeFormat;
lv_obj_t *ui_TheBar2;
void ui_event_BackToMenuFromSettings( lv_event_t * e);
lv_obj_t *ui_BackToMenuFromSettings;
void ui_event_BackHome( lv_event_t * e);
lv_obj_t *ui_BackHome;
lv_obj_t *ui_BarLabelSettings;
lv_obj_t *ui_CalendarSettings2;
void ui_event_CalendarDropdown2( lv_event_t * e);
lv_obj_t *ui_CalendarDropdown2;
lv_obj_t *ui_TimeFormat1;
// CUSTOM VARIABLES

// SCREEN: ui_CalendarInDetail
void ui_CalendarInDetail_screen_init(void);
lv_obj_t *ui_CalendarInDetail;
lv_obj_t *ui_CalendarImgBack;
lv_obj_t *ui_CalendarImgFront;
lv_obj_t *ui_CalendarDigit;
lv_obj_t *ui_CalendarCharacter;
lv_obj_t *ui_YearLabelZH;
lv_obj_t *ui_DateLabelZH;
lv_obj_t *ui_TermLabelZH;
lv_obj_t *ui_YearValueZH;
lv_obj_t *ui_DateValueZH;
lv_obj_t *ui_TermValueZH;
lv_obj_t *ui_TheBar3;
void ui_event_BackToMenuFromCalendar( lv_event_t * e);
lv_obj_t *ui_BackToMenuFromCalendar;
void ui_event_BackHomeFromCalendar( lv_event_t * e);
lv_obj_t *ui_BackHomeFromCalendar;
lv_obj_t *ui_Title;
lv_obj_t *ui_BarLabelCalendar;
// CUSTOM VARIABLES

// SCREEN: ui_ClockSettingPage
void ui_ClockSettingPage_screen_init(void);
lv_obj_t *ui_ClockSettingPage;
lv_obj_t *ui_RollerHour;
lv_obj_t *ui_RollerMin;
lv_obj_t *ui_RollerSec;
lv_obj_t *ui_SpiltterLeft;
lv_obj_t *ui_SpiltterRight;
lv_obj_t *ui_Sentence;
void ui_event_SetButton( lv_event_t * e);
lv_obj_t *ui_SetButton;
void ui_event_ResetBottom( lv_event_t * e);
lv_obj_t *ui_ResetBottom;
lv_obj_t *ui_SetButtonLabel;
lv_obj_t *ui_ResetButtonLabel;
lv_obj_t *ui_TheBar4;
void ui_event_BackHomeFromAlarm( lv_event_t * e);
lv_obj_t *ui_BackHomeFromAlarm;
void ui_event_BackToMenuFromAlarm( lv_event_t * e);
lv_obj_t *ui_BackToMenuFromAlarm;
lv_obj_t *ui_BarLabelAlarm;
void ui_event_TimesUpFlag( lv_event_t * e);
lv_obj_t *ui_TimesUpFlag;
// CUSTOM VARIABLES

// SCREEN: ui_TimesUpPage
void ui_TimesUpPage_screen_init(void);
void ui_event_TimesUpPage( lv_event_t * e);
lv_obj_t *ui_TimesUpPage;
lv_obj_t *ui_AlarmsOffICon;
lv_obj_t *ui_Notification;
void ui_event_GotchaBottom( lv_event_t * e);
lv_obj_t *ui_GotchaBottom;
lv_obj_t *ui_GotchaBottomLabel;
// CUSTOM VARIABLES

// SCREEN: ui_WeatherForcastPage
void ui_WeatherForcastPage_screen_init(void);
lv_obj_t *ui_WeatherForcastPage;
lv_obj_t *ui_TheBar5;
lv_obj_t *ui_BackBlock;
lv_obj_t *ui_Block1;
lv_obj_t *ui_WeatherLabel1;
lv_obj_t *ui_WeatherIcon1;
lv_obj_t *ui_WeatherIconLabel1;
lv_obj_t *ui_TemperatureLabel1;
lv_obj_t *ui_Temperature1;
lv_obj_t *ui_Precipitation1;
lv_obj_t *ui_PrecipitationLabel1;
lv_obj_t *ui_Block2;
lv_obj_t *ui_WeatherLabel2;
lv_obj_t *ui_WeatherIcon2;
lv_obj_t *ui_WeatherIconLabel2;
lv_obj_t *ui_TemperatureLabel2;
lv_obj_t *ui_Temperature2;
lv_obj_t *ui_Precipitation2;
lv_obj_t *ui_PrecipitationLabel2;
lv_obj_t *ui_Block3;
lv_obj_t *ui_WeatherLabel3;
lv_obj_t *ui_WeatherIcon3;
lv_obj_t *ui_WeatherIconLabel3;
lv_obj_t *ui_TemperatureLabel3;
lv_obj_t *ui_Temperature3;
lv_obj_t *ui_Precipitation3;
lv_obj_t *ui_PrecipitationLabel3;
lv_obj_t *ui_Block4;
lv_obj_t *ui_WeatherLabel4;
lv_obj_t *ui_WeatherIcon4;
lv_obj_t *ui_WeatherIconLabel4;
lv_obj_t *ui_TemperatureLabel4;
lv_obj_t *ui_Temperature4;
lv_obj_t *ui_Precipitation4;
lv_obj_t *ui_PrecipitationLabel4;
lv_obj_t *ui_Block5;
lv_obj_t *ui_WeatherLabel5;
lv_obj_t *ui_WeatherIcon5;
lv_obj_t *ui_WeatherIconLabel5;
lv_obj_t *ui_TemperatureLabel5;
lv_obj_t *ui_Temperature5;
lv_obj_t *ui_Precipitation5;
lv_obj_t *ui_PrecipitationLabel5;
void ui_event_FromWeatherBackToMenu( lv_event_t * e);
lv_obj_t *ui_FromWeatherBackToMenu;
lv_obj_t *ui_WeatherBarLabel;
void ui_event_WeatherRefreshIcon( lv_event_t * e);
lv_obj_t *ui_WeatherRefreshIcon;
lv_obj_t *ui_WeatherRefreshNotice;
lv_obj_t *ui_WeatherRefreshNoticeSpinner;
lv_obj_t *ui_WeatherRefreshNoticeLabel;
lv_obj_t *ui_WeatherRefreshAcceptIcon;
lv_obj_t *ui_WeatherRefreshDeclineIcon;
// CUSTOM VARIABLES

// SCREEN: ui_HumidityPage
void ui_HumidityPage_screen_init(void);
lv_obj_t *ui_HumidityPage;
lv_obj_t *ui_TheBar6;
void ui_event_FromHumidityBackToMenu( lv_event_t * e);
lv_obj_t *ui_FromHumidityBackToMenu;
lv_obj_t *ui_BarLabelHumidity;
void ui_event_BackHomeFromHumidity( lv_event_t * e);
lv_obj_t *ui_BackHomeFromHumidity;
lv_obj_t *ui_HumidityDeco;
lv_obj_t *ui_InTemperatureLabel;
lv_obj_t *ui_InHumidityLabel;
lv_obj_t *ui_Label34;
lv_obj_t *ui_Label1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void AlarmIconBouncing_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, 0, 10 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);

}
void WeatherRefreshNotice_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 0, 130 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_1, 0, -130 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_1, delay + 2000 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_GoMenu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MenuPage, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MenuPage_screen_init);
}
}

void ui_event_BackToClockBottom( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ClockPage, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ClockPage_screen_init);
}
}

void ui_event_SettingsIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SettingsPage, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SettingsPage_screen_init);
}
}

void ui_event_CalendarIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_CalendarInDetail, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_CalendarInDetail_screen_init);
}
}

void ui_event_AlarmIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ClockSettingPage, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ClockSettingPage_screen_init);
}
}

void ui_event_WeatherIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_WeatherForcastPage, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_WeatherForcastPage_screen_init);
}
}

void ui_event_HumidityIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_HumidityPage, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_HumidityPage_screen_init);
}
}

void ui_event_CalendarDropdown1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      TimeFormatChange_cb_handler( e );
}
}

void ui_event_BackToMenuFromSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MenuPage, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuPage_screen_init);
}
}

void ui_event_BackHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ClockPage, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ClockPage_screen_init);
}
}

void ui_event_CalendarDropdown2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      RingtoneChange_cb_Handler( e );
}
}

void ui_event_BackToMenuFromCalendar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MenuPage, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuPage_screen_init);
}
}

void ui_event_BackHomeFromCalendar( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ClockPage, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ClockPage_screen_init);
}
}

void ui_event_SetButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_RollerHour, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_RollerSec, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_RollerMin, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_SetButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      SetButtom_cb_Handler( e );
}
}

void ui_event_ResetBottom( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_SetButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_RollerHour, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_RollerMin, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_RollerSec, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      ResetButtom_cb_Handler( e );
      _ui_roller_set_property(ui_RollerHour, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 8);
      _ui_roller_set_property(ui_RollerMin, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 0);
      _ui_roller_set_property(ui_RollerSec, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 0);
}
}

void ui_event_BackHomeFromAlarm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ClockPage, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ClockPage_screen_init);
}
}

void ui_event_BackToMenuFromAlarm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MenuPage, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuPage_screen_init);
}
}

void ui_event_TimesUpFlag( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_screen_change( &ui_TimesUpPage, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_TimesUpPage_screen_init);
}
}

void ui_event_TimesUpPage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      AlarmIconBouncing_Animation(ui_AlarmsOffICon, 0);
}
}

void ui_event_GotchaBottom( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_roller_set_property(ui_RollerHour, _UI_ROLLER_PROPERTY_SELECTED, 8);
      _ui_roller_set_property(ui_RollerMin, _UI_ROLLER_PROPERTY_SELECTED, 0);
      _ui_roller_set_property(ui_RollerSec, _UI_ROLLER_PROPERTY_SELECTED, 0);
      GotchaBottom_cb_Handler( e );
      _ui_screen_change( &ui_ClockPage, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ClockPage_screen_init);
      _ui_state_modify( ui_RollerHour, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_RollerMin, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_RollerSec, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
      _ui_state_modify( ui_SetButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
}
}

void ui_event_FromWeatherBackToMenu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MenuPage, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuPage_screen_init);
}
}

void ui_event_WeatherRefreshIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      WeatherRefresh_cb_Handler( e );
      WeatherRefreshNotice_Animation(ui_WeatherRefreshNotice, 0);
}
}

void ui_event_FromHumidityBackToMenu( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MenuPage, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MenuPage_screen_init);
}
}

void ui_event_BackHomeFromHumidity( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ClockPage, LV_SCR_LOAD_ANIM_OVER_RIGHT, 500, 0, &ui_ClockPage_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ClockPage_screen_init();
ui_MenuPage_screen_init();
ui_SettingsPage_screen_init();
ui_CalendarInDetail_screen_init();
ui_ClockSettingPage_screen_init();
ui_TimesUpPage_screen_init();
ui_WeatherForcastPage_screen_init();
ui_HumidityPage_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ClockPage);
}
