// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#ifndef _THATCLOCK_UI_H
#define _THATCLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void AlarmIconBouncing_Animation( lv_obj_t *TargetObject, int delay);
void WeatherRefreshNotice_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_ClockPage
void ui_ClockPage_screen_init(void);
extern lv_obj_t *ui_ClockPage;
extern lv_obj_t *ui_TimeBlock;
extern lv_obj_t *ui_DateLabel;
void ui_event_GoMenu( lv_event_t * e);
extern lv_obj_t *ui_GoMenu;
extern lv_obj_t *ui_TimeBlock12H;
extern lv_obj_t *ui_LabelFor12H;
// CUSTOM VARIABLES

// SCREEN: ui_MenuPage
void ui_MenuPage_screen_init(void);
extern lv_obj_t *ui_MenuPage;
extern lv_obj_t *ui_TheBar;
void ui_event_BackToClockBottom( lv_event_t * e);
extern lv_obj_t *ui_BackToClockBottom;
extern lv_obj_t *ui_Disconnected;
extern lv_obj_t *ui_Connected;
extern lv_obj_t *ui_BarLabel;
void ui_event_SettingsIcon( lv_event_t * e);
extern lv_obj_t *ui_SettingsIcon;
extern lv_obj_t *ui_SettingsLabel;
void ui_event_CalendarIcon( lv_event_t * e);
extern lv_obj_t *ui_CalendarIcon;
extern lv_obj_t *ui_CalendarLabel;
void ui_event_AlarmIcon( lv_event_t * e);
extern lv_obj_t *ui_AlarmIcon;
extern lv_obj_t *ui_AlarmLabel;
void ui_event_WeatherIcon( lv_event_t * e);
extern lv_obj_t *ui_WeatherIcon;
extern lv_obj_t *ui_WeatherLabel;
void ui_event_HumidityIcon( lv_event_t * e);
extern lv_obj_t *ui_HumidityIcon;
extern lv_obj_t *ui_HumidityLabel;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsPage
void ui_SettingsPage_screen_init(void);
extern lv_obj_t *ui_SettingsPage;
extern lv_obj_t *ui_CalendarSettings1;
void ui_event_CalendarDropdown1( lv_event_t * e);
extern lv_obj_t *ui_CalendarDropdown1;
extern lv_obj_t *ui_TimeFormat;
extern lv_obj_t *ui_TheBar2;
void ui_event_BackToMenuFromSettings( lv_event_t * e);
extern lv_obj_t *ui_BackToMenuFromSettings;
void ui_event_BackHome( lv_event_t * e);
extern lv_obj_t *ui_BackHome;
extern lv_obj_t *ui_BarLabelSettings;
extern lv_obj_t *ui_CalendarSettings2;
void ui_event_CalendarDropdown2( lv_event_t * e);
extern lv_obj_t *ui_CalendarDropdown2;
extern lv_obj_t *ui_TimeFormat1;
// CUSTOM VARIABLES

// SCREEN: ui_CalendarInDetail
void ui_CalendarInDetail_screen_init(void);
extern lv_obj_t *ui_CalendarInDetail;
extern lv_obj_t *ui_CalendarImgBack;
extern lv_obj_t *ui_CalendarImgFront;
extern lv_obj_t *ui_CalendarDigit;
extern lv_obj_t *ui_CalendarCharacter;
extern lv_obj_t *ui_YearLabelZH;
extern lv_obj_t *ui_DateLabelZH;
extern lv_obj_t *ui_TermLabelZH;
extern lv_obj_t *ui_YearValueZH;
extern lv_obj_t *ui_DateValueZH;
extern lv_obj_t *ui_TermValueZH;
extern lv_obj_t *ui_TheBar3;
void ui_event_BackToMenuFromCalendar( lv_event_t * e);
extern lv_obj_t *ui_BackToMenuFromCalendar;
void ui_event_BackHomeFromCalendar( lv_event_t * e);
extern lv_obj_t *ui_BackHomeFromCalendar;
extern lv_obj_t *ui_Title;
extern lv_obj_t *ui_BarLabelCalendar;
// CUSTOM VARIABLES

// SCREEN: ui_ClockSettingPage
void ui_ClockSettingPage_screen_init(void);
extern lv_obj_t *ui_ClockSettingPage;
extern lv_obj_t *ui_RollerHour;
extern lv_obj_t *ui_RollerMin;
extern lv_obj_t *ui_RollerSec;
extern lv_obj_t *ui_SpiltterLeft;
extern lv_obj_t *ui_SpiltterRight;
extern lv_obj_t *ui_Sentence;
void ui_event_SetButton( lv_event_t * e);
extern lv_obj_t *ui_SetButton;
void ui_event_ResetBottom( lv_event_t * e);
extern lv_obj_t *ui_ResetBottom;
extern lv_obj_t *ui_SetButtonLabel;
extern lv_obj_t *ui_ResetButtonLabel;
extern lv_obj_t *ui_TheBar4;
void ui_event_BackHomeFromAlarm( lv_event_t * e);
extern lv_obj_t *ui_BackHomeFromAlarm;
void ui_event_BackToMenuFromAlarm( lv_event_t * e);
extern lv_obj_t *ui_BackToMenuFromAlarm;
extern lv_obj_t *ui_BarLabelAlarm;
void ui_event_TimesUpFlag( lv_event_t * e);
extern lv_obj_t *ui_TimesUpFlag;
// CUSTOM VARIABLES

// SCREEN: ui_TimesUpPage
void ui_TimesUpPage_screen_init(void);
void ui_event_TimesUpPage( lv_event_t * e);
extern lv_obj_t *ui_TimesUpPage;
extern lv_obj_t *ui_AlarmsOffICon;
extern lv_obj_t *ui_Notification;
void ui_event_GotchaBottom( lv_event_t * e);
extern lv_obj_t *ui_GotchaBottom;
extern lv_obj_t *ui_GotchaBottomLabel;
// CUSTOM VARIABLES

// SCREEN: ui_WeatherForcastPage
void ui_WeatherForcastPage_screen_init(void);
extern lv_obj_t *ui_WeatherForcastPage;
extern lv_obj_t *ui_TheBar5;
extern lv_obj_t *ui_BackBlock;
extern lv_obj_t *ui_Block1;
extern lv_obj_t *ui_WeatherLabel1;
extern lv_obj_t *ui_WeatherIcon1;
extern lv_obj_t *ui_WeatherIconLabel1;
extern lv_obj_t *ui_TemperatureLabel1;
extern lv_obj_t *ui_Temperature1;
extern lv_obj_t *ui_Precipitation1;
extern lv_obj_t *ui_PrecipitationLabel1;
extern lv_obj_t *ui_Block2;
extern lv_obj_t *ui_WeatherLabel2;
extern lv_obj_t *ui_WeatherIcon2;
extern lv_obj_t *ui_WeatherIconLabel2;
extern lv_obj_t *ui_TemperatureLabel2;
extern lv_obj_t *ui_Temperature2;
extern lv_obj_t *ui_Precipitation2;
extern lv_obj_t *ui_PrecipitationLabel2;
extern lv_obj_t *ui_Block3;
extern lv_obj_t *ui_WeatherLabel3;
extern lv_obj_t *ui_WeatherIcon3;
extern lv_obj_t *ui_WeatherIconLabel3;
extern lv_obj_t *ui_TemperatureLabel3;
extern lv_obj_t *ui_Temperature3;
extern lv_obj_t *ui_Precipitation3;
extern lv_obj_t *ui_PrecipitationLabel3;
extern lv_obj_t *ui_Block4;
extern lv_obj_t *ui_WeatherLabel4;
extern lv_obj_t *ui_WeatherIcon4;
extern lv_obj_t *ui_WeatherIconLabel4;
extern lv_obj_t *ui_TemperatureLabel4;
extern lv_obj_t *ui_Temperature4;
extern lv_obj_t *ui_Precipitation4;
extern lv_obj_t *ui_PrecipitationLabel4;
extern lv_obj_t *ui_Block5;
extern lv_obj_t *ui_WeatherLabel5;
extern lv_obj_t *ui_WeatherIcon5;
extern lv_obj_t *ui_WeatherIconLabel5;
extern lv_obj_t *ui_TemperatureLabel5;
extern lv_obj_t *ui_Temperature5;
extern lv_obj_t *ui_Precipitation5;
extern lv_obj_t *ui_PrecipitationLabel5;
void ui_event_FromWeatherBackToMenu( lv_event_t * e);
extern lv_obj_t *ui_FromWeatherBackToMenu;
extern lv_obj_t *ui_WeatherBarLabel;
void ui_event_WeatherRefreshIcon( lv_event_t * e);
extern lv_obj_t *ui_WeatherRefreshIcon;
extern lv_obj_t *ui_WeatherRefreshNotice;
extern lv_obj_t *ui_WeatherRefreshNoticeSpinner;
extern lv_obj_t *ui_WeatherRefreshNoticeLabel;
extern lv_obj_t *ui_WeatherRefreshAcceptIcon;
extern lv_obj_t *ui_WeatherRefreshDeclineIcon;
// CUSTOM VARIABLES

// SCREEN: ui_HumidityPage
void ui_HumidityPage_screen_init(void);
extern lv_obj_t *ui_HumidityPage;
extern lv_obj_t *ui_TheBar6;
void ui_event_FromHumidityBackToMenu( lv_event_t * e);
extern lv_obj_t *ui_FromHumidityBackToMenu;
extern lv_obj_t *ui_BarLabelHumidity;
void ui_event_BackHomeFromHumidity( lv_event_t * e);
extern lv_obj_t *ui_BackHomeFromHumidity;
extern lv_obj_t *ui_HumidityDeco;
extern lv_obj_t *ui_InTemperatureLabel;
extern lv_obj_t *ui_InHumidityLabel;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Label1;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1234665140);   // assets/network-signal.png
LV_IMG_DECLARE( ui_img_network_png);   // assets/network.png
LV_IMG_DECLARE( ui_img_settings_png);   // assets/settings.png
LV_IMG_DECLARE( ui_img_calendaricon_png);   // assets/calendaricon.png
LV_IMG_DECLARE( ui_img_clock_png);   // assets/clock.png
LV_IMG_DECLARE( ui_img_cloud_png);   // assets/cloud.png
LV_IMG_DECLARE( ui_img_humidity_png);   // assets/humidity.png
LV_IMG_DECLARE( ui_img_home_png);   // assets/home.png
LV_IMG_DECLARE( ui_img_notification_png);   // assets/notification.png
LV_IMG_DECLARE( ui_img_sunny_s_cloudy_png);   // assets/sunny_s_cloudy.png
LV_IMG_DECLARE( ui_img_refresh_png);   // assets/refresh.png
LV_IMG_DECLARE( ui_img_accept_png);   // assets/accept.png
LV_IMG_DECLARE( ui_img_decline_png);   // assets/decline.png
LV_IMG_DECLARE( ui_img_1176433851);   // assets/water-temperature.png
LV_IMG_DECLARE( ui_img_cloudy_png);   // assets/cloudy.png
LV_IMG_DECLARE( ui_img_cloudy_s_rain_png);   // assets/cloudy_s_rain.png
LV_IMG_DECLARE( ui_img_cloudy_s_snow_png);   // assets/cloudy_s_snow.png
LV_IMG_DECLARE( ui_img_cloudy_s_sunny_png);   // assets/cloudy_s_sunny.png
LV_IMG_DECLARE( ui_img_fog_png);   // assets/fog.png
LV_IMG_DECLARE( ui_img_partly_cloudy_png);   // assets/partly_cloudy.png
LV_IMG_DECLARE( ui_img_rain_png);   // assets/rain.png
LV_IMG_DECLARE( ui_img_rain_heavy_png);   // assets/rain_heavy.png
LV_IMG_DECLARE( ui_img_rain_light_png);   // assets/rain_light.png
LV_IMG_DECLARE( ui_img_rain_s_cloudy_png);   // assets/rain_s_cloudy.png
LV_IMG_DECLARE( ui_img_rain_s_snow_png);   // assets/rain_s_snow.png
LV_IMG_DECLARE( ui_img_rain_s_sunny_png);   // assets/rain_s_sunny.png
LV_IMG_DECLARE( ui_img_snow_png);   // assets/snow.png
LV_IMG_DECLARE( ui_img_snow_heavy_png);   // assets/snow_heavy.png
LV_IMG_DECLARE( ui_img_snow_light_png);   // assets/snow_light.png
LV_IMG_DECLARE( ui_img_snow_s_cloudy_png);   // assets/snow_s_cloudy.png
LV_IMG_DECLARE( ui_img_snow_s_rain_png);   // assets/snow_s_rain.png
LV_IMG_DECLARE( ui_img_sunny_png);   // assets/sunny.png
LV_IMG_DECLARE( ui_img_sunny_s_rain_png);   // assets/sunny_s_rain.png
LV_IMG_DECLARE( ui_img_thunderstorms_png);   // assets/thunderstorms.png

// FONTS
LV_FONT_DECLARE( ui_font_CharacterForCalendar);
LV_FONT_DECLARE( ui_font_Clock);
LV_FONT_DECLARE( ui_font_NumberForCalendar);
LV_FONT_DECLARE( ui_font_ZH);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
