// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void ui_ClockSettingPage_screen_init(void)
{
ui_ClockSettingPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ClockSettingPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RollerHour = lv_roller_create(ui_ClockSettingPage);
lv_roller_set_options( ui_RollerHour, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23", LV_ROLLER_MODE_INFINITE );
lv_roller_set_selected( ui_RollerHour, 8, LV_ANIM_OFF);
lv_obj_set_width( ui_RollerHour, 64);
lv_obj_set_height( ui_RollerHour, 64);
lv_obj_set_x( ui_RollerHour, -100 );
lv_obj_set_y( ui_RollerHour, -10 );
lv_obj_set_align( ui_RollerHour, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_RollerHour, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RollerHour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RollerHour, &ui_font_Clock, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_RollerHour, lv_color_hex(0x73AAFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RollerHour, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RollerHour, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RollerHour, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_RollerMin = lv_roller_create(ui_ClockSettingPage);
lv_roller_set_options( ui_RollerMin, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_RollerMin, 64);
lv_obj_set_height( ui_RollerMin, 64);
lv_obj_set_x( ui_RollerMin, 0 );
lv_obj_set_y( ui_RollerMin, -10 );
lv_obj_set_align( ui_RollerMin, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_RollerMin, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RollerMin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RollerMin, &ui_font_Clock, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_RollerMin, lv_color_hex(0x73AAFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RollerMin, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RollerMin, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RollerMin, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_RollerSec = lv_roller_create(ui_ClockSettingPage);
lv_roller_set_options( ui_RollerSec, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_RollerSec, 64);
lv_obj_set_height( ui_RollerSec, 64);
lv_obj_set_x( ui_RollerSec, 100 );
lv_obj_set_y( ui_RollerSec, -10 );
lv_obj_set_align( ui_RollerSec, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_RollerSec, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RollerSec, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RollerSec, &ui_font_Clock, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_RollerSec, lv_color_hex(0x73AAFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RollerSec, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RollerSec, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RollerSec, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_SpiltterLeft = lv_label_create(ui_ClockSettingPage);
lv_obj_set_width( ui_SpiltterLeft, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpiltterLeft, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpiltterLeft, -50 );
lv_obj_set_y( ui_SpiltterLeft, -10 );
lv_obj_set_align( ui_SpiltterLeft, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpiltterLeft,":");
lv_obj_set_style_text_font(ui_SpiltterLeft, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpiltterRight = lv_label_create(ui_ClockSettingPage);
lv_obj_set_width( ui_SpiltterRight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpiltterRight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpiltterRight, 50 );
lv_obj_set_y( ui_SpiltterRight, -10 );
lv_obj_set_align( ui_SpiltterRight, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpiltterRight,":");
lv_obj_set_style_text_font(ui_SpiltterRight, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sentence = lv_label_create(ui_ClockSettingPage);
lv_obj_set_width( ui_Sentence, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Sentence, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Sentence, -40 );
lv_obj_set_y( ui_Sentence, -70 );
lv_obj_set_align( ui_Sentence, LV_ALIGN_CENTER );
lv_label_set_text(ui_Sentence,"The alarm will remind you at:");

ui_SetButton = lv_button_create(ui_ClockSettingPage);
lv_obj_set_width( ui_SetButton, 100);
lv_obj_set_height( ui_SetButton, 40);
lv_obj_set_x( ui_SetButton, -65 );
lv_obj_set_y( ui_SetButton, 60 );
lv_obj_set_align( ui_SetButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_SetButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SetButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SetButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ResetBottom = lv_button_create(ui_ClockSettingPage);
lv_obj_set_width( ui_ResetBottom, 100);
lv_obj_set_height( ui_ResetBottom, 40);
lv_obj_set_x( ui_ResetBottom, 65 );
lv_obj_set_y( ui_ResetBottom, 60 );
lv_obj_set_align( ui_ResetBottom, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ResetBottom, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_ResetBottom, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ResetBottom, lv_color_hex(0x73AAFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ResetBottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetButtonLabel = lv_label_create(ui_ClockSettingPage);
lv_obj_set_width( ui_SetButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetButtonLabel, -65 );
lv_obj_set_y( ui_SetButtonLabel, 60 );
lv_obj_set_align( ui_SetButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetButtonLabel,"Set");

ui_ResetButtonLabel = lv_label_create(ui_ClockSettingPage);
lv_obj_set_width( ui_ResetButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ResetButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ResetButtonLabel, 65 );
lv_obj_set_y( ui_ResetButtonLabel, 60 );
lv_obj_set_align( ui_ResetButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ResetButtonLabel,"Reset");
lv_obj_set_style_text_color(ui_ResetButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ResetButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TheBar4 = lv_obj_create(ui_ClockSettingPage);
lv_obj_set_width( ui_TheBar4, 322);
lv_obj_set_height( ui_TheBar4, 33);
lv_obj_set_x( ui_TheBar4, 0 );
lv_obj_set_y( ui_TheBar4, -105 );
lv_obj_set_align( ui_TheBar4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TheBar4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TheBar4, lv_color_hex(0xDEF6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TheBar4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackHomeFromAlarm = lv_image_create(ui_ClockSettingPage);
lv_image_set_src(ui_BackHomeFromAlarm, &ui_img_home_png);
lv_obj_set_width( ui_BackHomeFromAlarm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackHomeFromAlarm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackHomeFromAlarm, 139 );
lv_obj_set_y( ui_BackHomeFromAlarm, -105 );
lv_obj_set_align( ui_BackHomeFromAlarm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackHomeFromAlarm, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_BackHomeFromAlarm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_BackHomeFromAlarm,10);

ui_BackToMenuFromAlarm = lv_label_create(ui_ClockSettingPage);
lv_obj_set_width( ui_BackToMenuFromAlarm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackToMenuFromAlarm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackToMenuFromAlarm, -125 );
lv_obj_set_y( ui_BackToMenuFromAlarm, -106 );
lv_obj_set_align( ui_BackToMenuFromAlarm, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackToMenuFromAlarm,"< Back");
lv_obj_add_flag( ui_BackToMenuFromAlarm, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_BackToMenuFromAlarm, lv_color_hex(0x3BC9FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackToMenuFromAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarLabelAlarm = lv_label_create(ui_ClockSettingPage);
lv_obj_set_width( ui_BarLabelAlarm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BarLabelAlarm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BarLabelAlarm, 0 );
lv_obj_set_y( ui_BarLabelAlarm, -105 );
lv_obj_set_align( ui_BarLabelAlarm, LV_ALIGN_CENTER );
lv_label_set_text(ui_BarLabelAlarm,"Alarm");

ui_TimesUpFlag = lv_switch_create(ui_ClockSettingPage);
lv_obj_set_x( ui_TimesUpFlag, 109 );
lv_obj_set_y( ui_TimesUpFlag, -65 );
lv_obj_set_align( ui_TimesUpFlag, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TimesUpFlag, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_TimesUpFlag, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags

lv_obj_add_event_cb(ui_SetButton, ui_event_SetButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ResetBottom, ui_event_ResetBottom, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackHomeFromAlarm, ui_event_BackHomeFromAlarm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackToMenuFromAlarm, ui_event_BackToMenuFromAlarm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TimesUpFlag, ui_event_TimesUpFlag, LV_EVENT_ALL, NULL);

}
