// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#ifndef _THATCLOCK_UI_COMP_HOOK_H
#define _THATCLOCK_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_CalendarSettings_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
