// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void ui_CalendarInDetail_screen_init(void)
{
ui_CalendarInDetail = lv_obj_create(NULL);
lv_obj_remove_flag( ui_CalendarInDetail, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CalendarImgBack = lv_obj_create(ui_CalendarInDetail);
lv_obj_set_width( ui_CalendarImgBack, 142);
lv_obj_set_height( ui_CalendarImgBack, 165);
lv_obj_set_x( ui_CalendarImgBack, 80 );
lv_obj_set_y( ui_CalendarImgBack, 0 );
lv_obj_set_align( ui_CalendarImgBack, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_CalendarImgBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CalendarImgBack, lv_color_hex(0x73A8FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CalendarImgBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CalendarImgFront = lv_obj_create(ui_CalendarInDetail);
lv_obj_set_width( ui_CalendarImgFront, 100);
lv_obj_set_height( ui_CalendarImgFront, 84);
lv_obj_set_x( ui_CalendarImgFront, 82 );
lv_obj_set_y( ui_CalendarImgFront, 18 );
lv_obj_set_align( ui_CalendarImgFront, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_CalendarImgFront, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CalendarDigit = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_CalendarDigit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalendarDigit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalendarDigit, 80 );
lv_obj_set_y( ui_CalendarDigit, 22 );
lv_obj_set_align( ui_CalendarDigit, LV_ALIGN_CENTER );
lv_label_set_text(ui_CalendarDigit,"01");
lv_obj_set_style_text_color(ui_CalendarDigit, lv_color_hex(0x73AAFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CalendarDigit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CalendarDigit, &ui_font_NumberForCalendar, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CalendarCharacter = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_CalendarCharacter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalendarCharacter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalendarCharacter, 80 );
lv_obj_set_y( ui_CalendarCharacter, -48 );
lv_obj_set_align( ui_CalendarCharacter, LV_ALIGN_CENTER );
lv_label_set_text(ui_CalendarCharacter,"JANUARY");
lv_obj_set_style_text_color(ui_CalendarCharacter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CalendarCharacter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CalendarCharacter, &ui_font_CharacterForCalendar, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_YearLabelZH = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_YearLabelZH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_YearLabelZH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_YearLabelZH, -125 );
lv_obj_set_y( ui_YearLabelZH, -30 );
lv_obj_set_align( ui_YearLabelZH, LV_ALIGN_CENTER );
lv_label_set_text(ui_YearLabelZH,"年份");
lv_obj_set_style_text_font(ui_YearLabelZH, &ui_font_ZH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateLabelZH = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_DateLabelZH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateLabelZH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateLabelZH, -125 );
lv_obj_set_y( ui_DateLabelZH, 0 );
lv_obj_set_align( ui_DateLabelZH, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateLabelZH,"日期");
lv_obj_set_style_text_font(ui_DateLabelZH, &ui_font_ZH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TermLabelZH = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_TermLabelZH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TermLabelZH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TermLabelZH, -125 );
lv_obj_set_y( ui_TermLabelZH, 30 );
lv_obj_set_align( ui_TermLabelZH, LV_ALIGN_CENTER );
lv_label_set_text(ui_TermLabelZH,"節氣");
lv_obj_set_style_text_font(ui_TermLabelZH, &ui_font_ZH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_YearValueZH = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_YearValueZH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_YearValueZH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_YearValueZH, -45 );
lv_obj_set_y( ui_YearValueZH, -30 );
lv_obj_set_align( ui_YearValueZH, LV_ALIGN_CENTER );
lv_label_set_text(ui_YearValueZH,"1900年");
lv_obj_set_style_text_font(ui_YearValueZH, &ui_font_ZH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateValueZH = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_DateValueZH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateValueZH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateValueZH, -45 );
lv_obj_set_y( ui_DateValueZH, 0 );
lv_obj_set_align( ui_DateValueZH, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateValueZH,"01月01日");
lv_obj_set_style_text_font(ui_DateValueZH, &ui_font_ZH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TermValueZH = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_TermValueZH, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TermValueZH, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TermValueZH, -45 );
lv_obj_set_y( ui_TermValueZH, 30 );
lv_obj_set_align( ui_TermValueZH, LV_ALIGN_CENTER );
lv_label_set_text(ui_TermValueZH,"冬至");
lv_obj_set_style_text_font(ui_TermValueZH, &ui_font_ZH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TheBar3 = lv_obj_create(ui_CalendarInDetail);
lv_obj_set_width( ui_TheBar3, 320);
lv_obj_set_height( ui_TheBar3, 33);
lv_obj_set_x( ui_TheBar3, 0 );
lv_obj_set_y( ui_TheBar3, -106 );
lv_obj_set_align( ui_TheBar3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TheBar3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TheBar3, lv_color_hex(0xDFF6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TheBar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackToMenuFromCalendar = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_BackToMenuFromCalendar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackToMenuFromCalendar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackToMenuFromCalendar, -125 );
lv_obj_set_y( ui_BackToMenuFromCalendar, -106 );
lv_obj_set_align( ui_BackToMenuFromCalendar, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackToMenuFromCalendar,"< Back");
lv_obj_add_flag( ui_BackToMenuFromCalendar, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_BackToMenuFromCalendar, lv_color_hex(0x08BAF6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackToMenuFromCalendar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackHomeFromCalendar = lv_image_create(ui_CalendarInDetail);
lv_image_set_src(ui_BackHomeFromCalendar, &ui_img_home_png);
lv_obj_set_width( ui_BackHomeFromCalendar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackHomeFromCalendar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackHomeFromCalendar, 139 );
lv_obj_set_y( ui_BackHomeFromCalendar, -105 );
lv_obj_set_align( ui_BackHomeFromCalendar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackHomeFromCalendar, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_BackHomeFromCalendar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_BackHomeFromCalendar,10);

ui_Title = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Title, -125 );
lv_obj_set_y( ui_Title, -60 );
lv_obj_set_align( ui_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_Title,"农历");
lv_obj_set_style_text_font(ui_Title, &ui_font_ZH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarLabelCalendar = lv_label_create(ui_CalendarInDetail);
lv_obj_set_width( ui_BarLabelCalendar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BarLabelCalendar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BarLabelCalendar, 0 );
lv_obj_set_y( ui_BarLabelCalendar, -105 );
lv_obj_set_align( ui_BarLabelCalendar, LV_ALIGN_CENTER );
lv_label_set_text(ui_BarLabelCalendar,"Calendar");

lv_obj_add_event_cb(ui_BackToMenuFromCalendar, ui_event_BackToMenuFromCalendar, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackHomeFromCalendar, ui_event_BackHomeFromCalendar, LV_EVENT_ALL, NULL);

}
