// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#ifndef _UI_COMP_CALENDARSETTINGS_H
#define _UI_COMP_CALENDARSETTINGS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT CalendarSettings
#define UI_COMP_CALENDARSETTINGS_CALENDARSETTINGS 0
#define _UI_COMP_CALENDARSETTINGS_NUM 1
lv_obj_t *ui_CalendarSettings_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
