// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

// COMPONENT CalendarSettings

lv_obj_t *ui_CalendarSettings_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_CalendarSettings;
cui_CalendarSettings = lv_obj_create(comp_parent);
lv_obj_set_width( cui_CalendarSettings, 334);
lv_obj_set_height( cui_CalendarSettings, 50);
lv_obj_set_x( cui_CalendarSettings, 6 );
lv_obj_set_y( cui_CalendarSettings, -65 );
lv_obj_set_align( cui_CalendarSettings, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_CalendarSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CALENDARSETTINGS_NUM);
children[UI_COMP_CALENDARSETTINGS_CALENDARSETTINGS] = cui_CalendarSettings;
lv_obj_add_event_cb(cui_CalendarSettings, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_CalendarSettings, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_CalendarSettings_create_hook(cui_CalendarSettings);
return cui_CalendarSettings; 
}

