// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void ui_ClockPage_screen_init(void)
{
ui_ClockPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ClockPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TimeBlock = lv_label_create(ui_ClockPage);
lv_obj_set_width( ui_TimeBlock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeBlock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeBlock, 0 );
lv_obj_set_y( ui_TimeBlock, -30 );
lv_obj_set_align( ui_TimeBlock, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeBlock,"00:00");
lv_obj_set_style_text_color(ui_TimeBlock, lv_color_hex(0x0CBBF5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeBlock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_TimeBlock, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TimeBlock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeBlock, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_TimeBlock, 0, LV_PART_MAIN| LV_STATE_USER_1);

ui_DateLabel = lv_label_create(ui_ClockPage);
lv_obj_set_width( ui_DateLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateLabel, 0 );
lv_obj_set_y( ui_DateLabel, 8 );
lv_obj_set_align( ui_DateLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateLabel,"2025/01/01");
lv_obj_set_style_text_letter_space(ui_DateLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_DateLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GoMenu = lv_label_create(ui_ClockPage);
lv_obj_set_width( ui_GoMenu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GoMenu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GoMenu, 0 );
lv_obj_set_y( ui_GoMenu, 40 );
lv_obj_set_align( ui_GoMenu, LV_ALIGN_CENTER );
lv_label_set_text(ui_GoMenu,"Click Here To Go To Menu >>");
lv_obj_add_flag( ui_GoMenu, LV_OBJ_FLAG_CLICKABLE );   /// Flags

ui_TimeBlock12H = lv_label_create(ui_ClockPage);
lv_obj_set_width( ui_TimeBlock12H, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeBlock12H, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeBlock12H, 0 );
lv_obj_set_y( ui_TimeBlock12H, -30 );
lv_obj_set_align( ui_TimeBlock12H, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeBlock12H,"00:00");
lv_obj_set_style_text_color(ui_TimeBlock12H, lv_color_hex(0x0CBBF5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeBlock12H, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_TimeBlock12H, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TimeBlock12H, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeBlock12H, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_TimeBlock12H, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_TimeBlock12H, 256, LV_PART_MAIN| LV_STATE_USER_1);

ui_LabelFor12H = lv_label_create(ui_ClockPage);
lv_obj_set_width( ui_LabelFor12H, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelFor12H, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelFor12H, 80 );
lv_obj_set_y( ui_LabelFor12H, -20 );
lv_obj_set_align( ui_LabelFor12H, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelFor12H,"AM");
lv_obj_set_style_transform_scale(ui_LabelFor12H, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_LabelFor12H, 256, LV_PART_MAIN| LV_STATE_USER_1);

lv_obj_add_event_cb(ui_GoMenu, ui_event_GoMenu, LV_EVENT_ALL, NULL);

}
