// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void TimeFormatChange_cb_handler(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	if(code == LV_EVENT_VALUE_CHANGED) {
		lv_obj_t *dropdown = lv_event_get_target(e);
		uint16_t selected_index = lv_dropdown_get_selected(dropdown);
		switch(selected_index){
			case 0:
				lv_obj_clear_state(ui_TimeBlock12H, LV_STATE_USER_1);
				lv_obj_clear_state(ui_LabelFor12H, LV_STATE_USER_1);
				lv_obj_clear_state(ui_TimeBlock, LV_STATE_USER_1);
				break;
			case 1:
				lv_obj_add_state(ui_TimeBlock12H, LV_STATE_USER_1);
				lv_obj_add_state(ui_LabelFor12H, LV_STATE_USER_1);
				lv_obj_add_state(ui_TimeBlock, LV_STATE_USER_1);
				break;
		}
	}
}


void SetButtom_cb_Handler(lv_event_t * e)
{
	// Get the value from rollbar
	RollbarSetHour = (int)lv_roller_get_selected(ui_RollerHour);
	RollbarSetMin = (int)lv_roller_get_selected(ui_RollerMin);
	RollbarSetSec = (int)lv_roller_get_selected(ui_RollerSec);
	// Enable alarm
	alarmSet = 1;
}

void ResetButtom_cb_Handler(lv_event_t * e)
{
	// Disable alarm
	alarmSet = 0;
}

void GotchaBottom_cb_Handler(lv_event_t * e)
{
	alarmSet = 0;
/* 	beepEnable = 0; */
	sendByteArray(0xFF);
}
void WeatherRefresh_cb_Handler(lv_event_t * e)
{
	updateTheWeather(true);
}

void RingtoneChange_cb_Handler(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	if(code == LV_EVENT_VALUE_CHANGED) {
		lv_obj_t *dropdown = lv_event_get_target(e);
		uint16_t selected_index = lv_dropdown_get_selected(dropdown);
		switch(selected_index){
			case 0:
				currentRing = 0x00;
				// play ring001_demo
				sendByteArray(0x05);
				break;
			case 1:
				currentRing = 0x01;
				// play ring002_demo
				sendByteArray(0x06);
				break;
			case 2:
				currentRing = 0x02;
				// play ring003_demo
				sendByteArray(0x07);
				break;
			case 3:
				currentRing = 0x03;
				// play ring004_demo
				sendByteArray(0x08);
				break;
			case 4:
				currentRing = 0x04;
				// play ring005_demo
				sendByteArray(0x09);
				break;
		}
	}
}