// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

extern const lv_img_dsc_t ui_img_sunny_s_rain_png;
extern const lv_img_dsc_t ui_img_sunny_s_cloudy_png;
extern const lv_img_dsc_t ui_img_sunny_png;
extern const lv_img_dsc_t ui_img_snow_s_rain_png;
extern const lv_img_dsc_t ui_img_snow_s_cloudy_png;
extern const lv_img_dsc_t ui_img_snow_light_png;
extern const lv_img_dsc_t ui_img_snow_heavy_png;
extern const lv_img_dsc_t ui_img_snow_png;
extern const lv_img_dsc_t ui_img_rain_s_sunny_png;
extern const lv_img_dsc_t ui_img_rain_s_snow_png;
extern const lv_img_dsc_t ui_img_rain_s_cloudy_png;
extern const lv_img_dsc_t ui_img_rain_light_png;
extern const lv_img_dsc_t ui_img_rain_heavy_png;
extern const lv_img_dsc_t ui_img_rain_png;
extern const lv_img_dsc_t ui_img_partly_cloudy_png;
extern const lv_img_dsc_t ui_img_fog_png;
extern const lv_img_dsc_t ui_img_cloudy_png;
extern const lv_img_dsc_t ui_img_cloudy_s_rain_png;
extern const lv_img_dsc_t ui_img_cloudy_s_snow_png;
extern const lv_img_dsc_t ui_img_cloudy_s_sunny_png;
extern const lv_img_dsc_t ui_img_thunderstorms_png;
extern const lv_img_dsc_t ui_img_accept_png;
extern const lv_img_dsc_t ui_img_decline_png;
extern int RollbarSetHour;
extern int RollbarSetMin;
extern int RollbarSetSec;
extern bool alarmSet; // Alarm enable flag
/* extern bool beepEnable; // Beep enable flag */
extern uint8_t currentRing; // Current ring

static const lv_img_dsc_t * img_icon_option[] = {
    &ui_img_sunny_s_rain_png,
    &ui_img_sunny_s_cloudy_png,
    &ui_img_sunny_png,
    &ui_img_snow_s_rain_png,
    &ui_img_snow_s_cloudy_png,
    &ui_img_snow_light_png,
    &ui_img_snow_heavy_png,
    &ui_img_snow_png,
    &ui_img_rain_s_sunny_png,
    &ui_img_rain_s_snow_png,
    &ui_img_rain_s_cloudy_png,
    &ui_img_rain_light_png,
    &ui_img_rain_heavy_png,
    &ui_img_rain_png,
    &ui_img_partly_cloudy_png,
    &ui_img_fog_png,
    &ui_img_cloudy_png,
    &ui_img_cloudy_s_rain_png,
    &ui_img_cloudy_s_snow_png,
    &ui_img_cloudy_s_sunny_png,
    &ui_img_thunderstorms_png,
    &ui_img_accept_png,
    &ui_img_decline_png
};

void TimeFormatChange_cb_handler(lv_event_t * e);
void RingtoneChange_cb_Handler(lv_event_t * e);
void SetButtom_cb_Handler(lv_event_t * e);
void ResetButtom_cb_Handler(lv_event_t * e);
void GotchaBottom_cb_Handler(lv_event_t * e);
void WeatherRefresh_cb_Handler(lv_event_t * e);
extern bool updateTheWeather(bool haveSynchronized_server);
extern void sendByteArray(uint8_t value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
