// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void ui_HumidityPage_screen_init(void)
{
ui_HumidityPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_HumidityPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TheBar6 = lv_obj_create(ui_HumidityPage);
lv_obj_set_width( ui_TheBar6, 334);
lv_obj_set_height( ui_TheBar6, 33);
lv_obj_set_x( ui_TheBar6, 0 );
lv_obj_set_y( ui_TheBar6, -104 );
lv_obj_set_align( ui_TheBar6, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TheBar6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TheBar6, lv_color_hex(0xDEF6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TheBar6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FromHumidityBackToMenu = lv_label_create(ui_HumidityPage);
lv_obj_set_width( ui_FromHumidityBackToMenu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FromHumidityBackToMenu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FromHumidityBackToMenu, -122 );
lv_obj_set_y( ui_FromHumidityBackToMenu, -103 );
lv_obj_set_align( ui_FromHumidityBackToMenu, LV_ALIGN_CENTER );
lv_label_set_text(ui_FromHumidityBackToMenu,"< Back");
lv_obj_add_flag( ui_FromHumidityBackToMenu, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_FromHumidityBackToMenu, lv_color_hex(0x5BD2FD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FromHumidityBackToMenu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarLabelHumidity = lv_label_create(ui_HumidityPage);
lv_obj_set_width( ui_BarLabelHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BarLabelHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BarLabelHumidity, 11 );
lv_obj_set_y( ui_BarLabelHumidity, -104 );
lv_obj_set_align( ui_BarLabelHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_BarLabelHumidity,"Humidity & Temperature");

ui_BackHomeFromHumidity = lv_image_create(ui_HumidityPage);
lv_image_set_src(ui_BackHomeFromHumidity, &ui_img_home_png);
lv_obj_set_width( ui_BackHomeFromHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackHomeFromHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackHomeFromHumidity, 139 );
lv_obj_set_y( ui_BackHomeFromHumidity, -105 );
lv_obj_set_align( ui_BackHomeFromHumidity, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackHomeFromHumidity, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_BackHomeFromHumidity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_BackHomeFromHumidity,10);

ui_HumidityDeco = lv_image_create(ui_HumidityPage);
lv_image_set_src(ui_HumidityDeco, &ui_img_1176433851);
lv_obj_set_width( ui_HumidityDeco, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HumidityDeco, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HumidityDeco, -91 );
lv_obj_set_y( ui_HumidityDeco, 14 );
lv_obj_set_align( ui_HumidityDeco, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HumidityDeco, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_HumidityDeco, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_HumidityDeco,60);

ui_InTemperatureLabel = lv_label_create(ui_HumidityPage);
lv_obj_set_width( ui_InTemperatureLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InTemperatureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InTemperatureLabel, 56 );
lv_obj_set_y( ui_InTemperatureLabel, -58 );
lv_obj_set_align( ui_InTemperatureLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_InTemperatureLabel,"On-site \nSensed Temperature:");

ui_InHumidityLabel = lv_label_create(ui_HumidityPage);
lv_obj_set_width( ui_InHumidityLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InHumidityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InHumidityLabel, 46 );
lv_obj_set_y( ui_InHumidityLabel, 26 );
lv_obj_set_align( ui_InHumidityLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_InHumidityLabel,"On-site \nSensed Humidity:");

ui_Label34 = lv_label_create(ui_HumidityPage);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label34, 55 );
lv_obj_set_y( ui_Label34, -13 );
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"20°C");
lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_HumidityPage);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 55 );
lv_obj_set_y( ui_Label1, 65 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"80.1%");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_FromHumidityBackToMenu, ui_event_FromHumidityBackToMenu, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackHomeFromHumidity, ui_event_BackHomeFromHumidity, LV_EVENT_ALL, NULL);

}
