// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void ui_MenuPage_screen_init(void)
{
ui_MenuPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_MenuPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TheBar = lv_obj_create(ui_MenuPage);
lv_obj_set_width( ui_TheBar, 319);
lv_obj_set_height( ui_TheBar, 33);
lv_obj_set_x( ui_TheBar, -1 );
lv_obj_set_y( ui_TheBar, -3 );
lv_obj_set_align( ui_TheBar, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_TheBar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TheBar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TheBar, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TheBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_TheBar, lv_color_hex(0xCFF3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_TheBar, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackToClockBottom = lv_label_create(ui_MenuPage);
lv_obj_set_width( ui_BackToClockBottom, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackToClockBottom, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackToClockBottom, -125 );
lv_obj_set_y( ui_BackToClockBottom, -106 );
lv_obj_set_align( ui_BackToClockBottom, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackToClockBottom,"< Back");
lv_obj_add_flag( ui_BackToClockBottom, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_BackToClockBottom, lv_color_hex(0x08BAF6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackToClockBottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Disconnected = lv_image_create(ui_MenuPage);
lv_image_set_src(ui_Disconnected, &ui_img_1234665140);
lv_obj_set_width( ui_Disconnected, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Disconnected, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Disconnected, 138 );
lv_obj_set_y( ui_Disconnected, -106 );
lv_obj_set_align( ui_Disconnected, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Disconnected, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Disconnected, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Disconnected,10);
lv_obj_set_style_transform_scale(ui_Disconnected, 0, LV_PART_MAIN| LV_STATE_USER_1);

ui_Connected = lv_image_create(ui_MenuPage);
lv_image_set_src(ui_Connected, &ui_img_network_png);
lv_obj_set_width( ui_Connected, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Connected, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Connected, 139 );
lv_obj_set_y( ui_Connected, -105 );
lv_obj_set_align( ui_Connected, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Connected, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Connected, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Connected,9);
lv_obj_set_style_transform_scale(ui_Connected, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_Connected, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_BarLabel = lv_label_create(ui_MenuPage);
lv_obj_set_width( ui_BarLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BarLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BarLabel, 0 );
lv_obj_set_y( ui_BarLabel, -105 );
lv_obj_set_align( ui_BarLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BarLabel,"Menu");

ui_SettingsIcon = lv_image_create(ui_MenuPage);
lv_image_set_src(ui_SettingsIcon, &ui_img_settings_png);
lv_obj_set_width( ui_SettingsIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsIcon, -100 );
lv_obj_set_y( ui_SettingsIcon, -45 );
lv_obj_set_align( ui_SettingsIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_SettingsIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_SettingsIcon,27);

ui_SettingsLabel = lv_label_create(ui_MenuPage);
lv_obj_set_width( ui_SettingsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsLabel, -100 );
lv_obj_set_y( ui_SettingsLabel, 0 );
lv_obj_set_align( ui_SettingsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsLabel,"Settings");

ui_CalendarIcon = lv_image_create(ui_MenuPage);
lv_image_set_src(ui_CalendarIcon, &ui_img_calendaricon_png);
lv_obj_set_width( ui_CalendarIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalendarIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalendarIcon, 0 );
lv_obj_set_y( ui_CalendarIcon, -45 );
lv_obj_set_align( ui_CalendarIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CalendarIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_CalendarIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_CalendarIcon,26);

ui_CalendarLabel = lv_label_create(ui_MenuPage);
lv_obj_set_width( ui_CalendarLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CalendarLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CalendarLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CalendarLabel,"Calendar");

ui_AlarmIcon = lv_image_create(ui_MenuPage);
lv_image_set_src(ui_AlarmIcon, &ui_img_clock_png);
lv_obj_set_width( ui_AlarmIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AlarmIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AlarmIcon, 100 );
lv_obj_set_y( ui_AlarmIcon, -45 );
lv_obj_set_align( ui_AlarmIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AlarmIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_AlarmIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_AlarmIcon,27);

ui_AlarmLabel = lv_label_create(ui_MenuPage);
lv_obj_set_width( ui_AlarmLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AlarmLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AlarmLabel, 100 );
lv_obj_set_y( ui_AlarmLabel, 0 );
lv_obj_set_align( ui_AlarmLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AlarmLabel,"Clock");

ui_WeatherIcon = lv_image_create(ui_MenuPage);
lv_image_set_src(ui_WeatherIcon, &ui_img_cloud_png);
lv_obj_set_width( ui_WeatherIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherIcon, -100 );
lv_obj_set_y( ui_WeatherIcon, 45 );
lv_obj_set_align( ui_WeatherIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherIcon,30);

ui_WeatherLabel = lv_label_create(ui_MenuPage);
lv_obj_set_width( ui_WeatherLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherLabel, -100 );
lv_obj_set_y( ui_WeatherLabel, 90 );
lv_obj_set_align( ui_WeatherLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeatherLabel,"Weather");

ui_HumidityIcon = lv_image_create(ui_MenuPage);
lv_image_set_src(ui_HumidityIcon, &ui_img_humidity_png);
lv_obj_set_width( ui_HumidityIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HumidityIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HumidityIcon, 0 );
lv_obj_set_y( ui_HumidityIcon, 45 );
lv_obj_set_align( ui_HumidityIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HumidityIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_HumidityIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_HumidityIcon,25);

ui_HumidityLabel = lv_label_create(ui_MenuPage);
lv_obj_set_width( ui_HumidityLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HumidityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HumidityLabel, 0 );
lv_obj_set_y( ui_HumidityLabel, 90 );
lv_obj_set_align( ui_HumidityLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HumidityLabel,"Humidity&\nTemperature");

lv_obj_add_event_cb(ui_BackToClockBottom, ui_event_BackToClockBottom, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsIcon, ui_event_SettingsIcon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CalendarIcon, ui_event_CalendarIcon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AlarmIcon, ui_event_AlarmIcon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WeatherIcon, ui_event_WeatherIcon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HumidityIcon, ui_event_HumidityIcon, LV_EVENT_ALL, NULL);

}
