// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void ui_SettingsPage_screen_init(void)
{
ui_SettingsPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_SettingsPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CalendarSettings1 = lv_obj_create(ui_SettingsPage);
lv_obj_set_width( ui_CalendarSettings1, 334);
lv_obj_set_height( ui_CalendarSettings1, 50);
lv_obj_set_x( ui_CalendarSettings1, 6 );
lv_obj_set_y( ui_CalendarSettings1, -65 );
lv_obj_set_align( ui_CalendarSettings1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_CalendarSettings1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CalendarDropdown1 = lv_dropdown_create(ui_CalendarSettings1);
lv_dropdown_set_options( ui_CalendarDropdown1, "24h\n12h" );
lv_obj_set_width( ui_CalendarDropdown1, 106);
lv_obj_set_height( ui_CalendarDropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalendarDropdown1, 98 );
lv_obj_set_y( ui_CalendarDropdown1, 0 );
lv_obj_set_align( ui_CalendarDropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CalendarDropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_TimeFormat = lv_label_create(ui_CalendarSettings1);
lv_obj_set_width( ui_TimeFormat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeFormat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeFormat, -101 );
lv_obj_set_y( ui_TimeFormat, 1 );
lv_obj_set_align( ui_TimeFormat, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeFormat,"Time Format");

ui_TheBar2 = lv_obj_create(ui_SettingsPage);
lv_obj_set_width( ui_TheBar2, 319);
lv_obj_set_height( ui_TheBar2, 33);
lv_obj_set_x( ui_TheBar2, -1 );
lv_obj_set_y( ui_TheBar2, -3 );
lv_obj_set_align( ui_TheBar2, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_TheBar2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TheBar2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TheBar2, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TheBar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_TheBar2, lv_color_hex(0xCFF3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_TheBar2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackToMenuFromSettings = lv_label_create(ui_SettingsPage);
lv_obj_set_width( ui_BackToMenuFromSettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackToMenuFromSettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackToMenuFromSettings, -125 );
lv_obj_set_y( ui_BackToMenuFromSettings, -105 );
lv_obj_set_align( ui_BackToMenuFromSettings, LV_ALIGN_CENTER );
lv_label_set_text(ui_BackToMenuFromSettings,"< Back");
lv_obj_add_flag( ui_BackToMenuFromSettings, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_BackToMenuFromSettings, lv_color_hex(0x08BAF6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BackToMenuFromSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackHome = lv_image_create(ui_SettingsPage);
lv_image_set_src(ui_BackHome, &ui_img_home_png);
lv_obj_set_width( ui_BackHome, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BackHome, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BackHome, 139 );
lv_obj_set_y( ui_BackHome, -105 );
lv_obj_set_align( ui_BackHome, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BackHome, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_BackHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_BackHome,10);

ui_BarLabelSettings = lv_label_create(ui_SettingsPage);
lv_obj_set_width( ui_BarLabelSettings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BarLabelSettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BarLabelSettings, 0 );
lv_obj_set_y( ui_BarLabelSettings, -105 );
lv_obj_set_align( ui_BarLabelSettings, LV_ALIGN_CENTER );
lv_label_set_text(ui_BarLabelSettings,"Settings");

ui_CalendarSettings2 = lv_obj_create(ui_SettingsPage);
lv_obj_set_width( ui_CalendarSettings2, 334);
lv_obj_set_height( ui_CalendarSettings2, 50);
lv_obj_set_x( ui_CalendarSettings2, 5 );
lv_obj_set_y( ui_CalendarSettings2, -18 );
lv_obj_set_align( ui_CalendarSettings2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_CalendarSettings2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CalendarDropdown2 = lv_dropdown_create(ui_CalendarSettings2);
lv_dropdown_set_options( ui_CalendarDropdown2, "Ring001\nRing002\nRing003\nRing004\nRing005" );
lv_obj_set_width( ui_CalendarDropdown2, 106);
lv_obj_set_height( ui_CalendarDropdown2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CalendarDropdown2, 98 );
lv_obj_set_y( ui_CalendarDropdown2, 0 );
lv_obj_set_align( ui_CalendarDropdown2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CalendarDropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_TimeFormat1 = lv_label_create(ui_CalendarSettings2);
lv_obj_set_width( ui_TimeFormat1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeFormat1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeFormat1, -112 );
lv_obj_set_y( ui_TimeFormat1, 1 );
lv_obj_set_align( ui_TimeFormat1, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeFormat1,"Ringtone");

lv_obj_add_event_cb(ui_CalendarDropdown1, ui_event_CalendarDropdown1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackToMenuFromSettings, ui_event_BackToMenuFromSettings, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackHome, ui_event_BackHome, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CalendarDropdown2, ui_event_CalendarDropdown2, LV_EVENT_ALL, NULL);

}
