// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void ui_TimesUpPage_screen_init(void)
{
ui_TimesUpPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_TimesUpPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AlarmsOffICon = lv_image_create(ui_TimesUpPage);
lv_image_set_src(ui_AlarmsOffICon, &ui_img_notification_png);
lv_obj_set_width( ui_AlarmsOffICon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AlarmsOffICon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AlarmsOffICon, -90 );
lv_obj_set_y( ui_AlarmsOffICon, 0 );
lv_obj_set_align( ui_AlarmsOffICon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AlarmsOffICon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_AlarmsOffICon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_AlarmsOffICon,65);

ui_Notification = lv_label_create(ui_TimesUpPage);
lv_obj_set_width( ui_Notification, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Notification, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Notification, 70 );
lv_obj_set_y( ui_Notification, -20 );
lv_obj_set_align( ui_Notification, LV_ALIGN_CENTER );
lv_label_set_text(ui_Notification,"Your alarm's going off!");

ui_GotchaBottom = lv_button_create(ui_TimesUpPage);
lv_obj_set_width( ui_GotchaBottom, 100);
lv_obj_set_height( ui_GotchaBottom, 37);
lv_obj_set_x( ui_GotchaBottom, 70 );
lv_obj_set_y( ui_GotchaBottom, 23 );
lv_obj_set_align( ui_GotchaBottom, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_GotchaBottom, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_GotchaBottom, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_GotchaBottom, lv_color_hex(0xDEF6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GotchaBottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GotchaBottomLabel = lv_label_create(ui_TimesUpPage);
lv_obj_set_width( ui_GotchaBottomLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GotchaBottomLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GotchaBottomLabel, 70 );
lv_obj_set_y( ui_GotchaBottomLabel, 23 );
lv_obj_set_align( ui_GotchaBottomLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_GotchaBottomLabel,"Gotcha!");

lv_obj_add_event_cb(ui_GotchaBottom, ui_event_GotchaBottom, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TimesUpPage, ui_event_TimesUpPage, LV_EVENT_ALL, NULL);

}
