// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: ThatClock

#include "ui.h"

void ui_WeatherForcastPage_screen_init(void)
{
ui_WeatherForcastPage = lv_obj_create(NULL);
lv_obj_remove_flag( ui_WeatherForcastPage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scroll_dir(ui_WeatherForcastPage, LV_DIR_HOR);
lv_obj_set_scroll_snap_x(ui_WeatherForcastPage, LV_SCROLL_SNAP_START);

ui_TheBar5 = lv_obj_create(ui_WeatherForcastPage);
lv_obj_set_width( ui_TheBar5, 327);
lv_obj_set_height( ui_TheBar5, 33);
lv_obj_set_x( ui_TheBar5, 0 );
lv_obj_set_y( ui_TheBar5, -104 );
lv_obj_set_align( ui_TheBar5, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TheBar5, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_TheBar5, lv_color_hex(0xDEF6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TheBar5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackBlock = lv_obj_create(ui_WeatherForcastPage);
lv_obj_set_width( ui_BackBlock, 326);
lv_obj_set_height( ui_BackBlock, 178);
lv_obj_set_x( ui_BackBlock, -3 );
lv_obj_set_y( ui_BackBlock, 10 );
lv_obj_set_align( ui_BackBlock, LV_ALIGN_CENTER );
lv_obj_set_scroll_dir(ui_BackBlock, LV_DIR_HOR);
lv_obj_set_scroll_snap_x(ui_BackBlock, LV_SCROLL_SNAP_CENTER);

ui_Block1 = lv_obj_create(ui_BackBlock);
lv_obj_set_width( ui_Block1, 264);
lv_obj_set_height( ui_Block1, 165);
lv_obj_set_x( ui_Block1, -20 );
lv_obj_set_y( ui_Block1, 0 );
lv_obj_set_align( ui_Block1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Block1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeatherLabel1 = lv_label_create(ui_Block1);
lv_obj_set_width( ui_WeatherLabel1, 134);
lv_obj_set_height( ui_WeatherLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherLabel1, -53 );
lv_obj_set_y( ui_WeatherLabel1, -60 );
lv_obj_set_align( ui_WeatherLabel1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherLabel1,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherLabel1,"September, 27");

ui_WeatherIcon1 = lv_image_create(ui_Block1);
lv_image_set_src(ui_WeatherIcon1, &ui_img_sunny_s_cloudy_png);
lv_obj_set_width( ui_WeatherIcon1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherIcon1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherIcon1, -61 );
lv_obj_set_y( ui_WeatherIcon1, -6 );
lv_obj_set_align( ui_WeatherIcon1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherIcon1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherIcon1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherIcon1,100);

ui_WeatherIconLabel1 = lv_label_create(ui_Block1);
lv_obj_set_width( ui_WeatherIconLabel1, 100);
lv_obj_set_height( ui_WeatherIconLabel1, 20);
lv_obj_set_x( ui_WeatherIconLabel1, -62 );
lv_obj_set_y( ui_WeatherIconLabel1, 56 );
lv_obj_set_align( ui_WeatherIconLabel1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherIconLabel1,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherIconLabel1,"Sunny Cloudy");
lv_obj_set_style_text_align(ui_WeatherIconLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WeatherIconLabel1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureLabel1 = lv_label_create(ui_Block1);
lv_obj_set_width( ui_TemperatureLabel1, 95);
lv_obj_set_height( ui_TemperatureLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureLabel1, 59 );
lv_obj_set_y( ui_TemperatureLabel1, -52 );
lv_obj_set_align( ui_TemperatureLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureLabel1,"TemperatureRange");

ui_Temperature1 = lv_label_create(ui_Block1);
lv_obj_set_width( ui_Temperature1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature1, 62 );
lv_obj_set_y( ui_Temperature1, -11 );
lv_obj_set_align( ui_Temperature1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature1,"17~33°C");
lv_obj_set_style_text_font(ui_Temperature1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Precipitation1 = lv_label_create(ui_Block1);
lv_obj_set_width( ui_Precipitation1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Precipitation1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Precipitation1, 62 );
lv_obj_set_y( ui_Precipitation1, 51 );
lv_obj_set_align( ui_Precipitation1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Precipitation1,"100%");
lv_obj_set_style_text_font(ui_Precipitation1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrecipitationLabel1 = lv_label_create(ui_Block1);
lv_obj_set_width( ui_PrecipitationLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrecipitationLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrecipitationLabel1, 59 );
lv_obj_set_y( ui_PrecipitationLabel1, 20 );
lv_obj_set_align( ui_PrecipitationLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrecipitationLabel1,"Precipitation");

ui_Block2 = lv_obj_create(ui_BackBlock);
lv_obj_set_width( ui_Block2, 264);
lv_obj_set_height( ui_Block2, 165);
lv_obj_set_x( ui_Block2, 260 );
lv_obj_set_y( ui_Block2, 0 );
lv_obj_set_align( ui_Block2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Block2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeatherLabel2 = lv_label_create(ui_Block2);
lv_obj_set_width( ui_WeatherLabel2, 134);
lv_obj_set_height( ui_WeatherLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherLabel2, -53 );
lv_obj_set_y( ui_WeatherLabel2, -60 );
lv_obj_set_align( ui_WeatherLabel2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherLabel2,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherLabel2,"September, 27");

ui_WeatherIcon2 = lv_image_create(ui_Block2);
lv_image_set_src(ui_WeatherIcon2, &ui_img_sunny_s_cloudy_png);
lv_obj_set_width( ui_WeatherIcon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherIcon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherIcon2, -61 );
lv_obj_set_y( ui_WeatherIcon2, -6 );
lv_obj_set_align( ui_WeatherIcon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherIcon2, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherIcon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherIcon2,100);

ui_WeatherIconLabel2 = lv_label_create(ui_Block2);
lv_obj_set_width( ui_WeatherIconLabel2, 100);
lv_obj_set_height( ui_WeatherIconLabel2, 20);
lv_obj_set_x( ui_WeatherIconLabel2, -68 );
lv_obj_set_y( ui_WeatherIconLabel2, 56 );
lv_obj_set_align( ui_WeatherIconLabel2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherIconLabel2,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherIconLabel2,"Sunny Cloudy");
lv_obj_set_style_text_font(ui_WeatherIconLabel2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureLabel2 = lv_label_create(ui_Block2);
lv_obj_set_width( ui_TemperatureLabel2, 95);
lv_obj_set_height( ui_TemperatureLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureLabel2, 59 );
lv_obj_set_y( ui_TemperatureLabel2, -52 );
lv_obj_set_align( ui_TemperatureLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureLabel2,"TemperatureRange");

ui_Temperature2 = lv_label_create(ui_Block2);
lv_obj_set_width( ui_Temperature2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature2, 62 );
lv_obj_set_y( ui_Temperature2, -11 );
lv_obj_set_align( ui_Temperature2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature2,"17~33°C");
lv_obj_set_style_text_font(ui_Temperature2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Precipitation2 = lv_label_create(ui_Block2);
lv_obj_set_width( ui_Precipitation2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Precipitation2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Precipitation2, 62 );
lv_obj_set_y( ui_Precipitation2, 51 );
lv_obj_set_align( ui_Precipitation2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Precipitation2,"100%");
lv_obj_set_style_text_font(ui_Precipitation2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrecipitationLabel2 = lv_label_create(ui_Block2);
lv_obj_set_width( ui_PrecipitationLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrecipitationLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrecipitationLabel2, 59 );
lv_obj_set_y( ui_PrecipitationLabel2, 20 );
lv_obj_set_align( ui_PrecipitationLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrecipitationLabel2,"Precipitation");

ui_Block3 = lv_obj_create(ui_BackBlock);
lv_obj_set_width( ui_Block3, 264);
lv_obj_set_height( ui_Block3, 165);
lv_obj_set_x( ui_Block3, 540 );
lv_obj_set_y( ui_Block3, 0 );
lv_obj_set_align( ui_Block3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Block3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeatherLabel3 = lv_label_create(ui_Block3);
lv_obj_set_width( ui_WeatherLabel3, 134);
lv_obj_set_height( ui_WeatherLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherLabel3, -53 );
lv_obj_set_y( ui_WeatherLabel3, -60 );
lv_obj_set_align( ui_WeatherLabel3, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherLabel3,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherLabel3,"September, 27");

ui_WeatherIcon3 = lv_image_create(ui_Block3);
lv_image_set_src(ui_WeatherIcon3, &ui_img_sunny_s_cloudy_png);
lv_obj_set_width( ui_WeatherIcon3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherIcon3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherIcon3, -61 );
lv_obj_set_y( ui_WeatherIcon3, -6 );
lv_obj_set_align( ui_WeatherIcon3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherIcon3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherIcon3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherIcon3,100);

ui_WeatherIconLabel3 = lv_label_create(ui_Block3);
lv_obj_set_width( ui_WeatherIconLabel3, 100);
lv_obj_set_height( ui_WeatherIconLabel3, 20);
lv_obj_set_x( ui_WeatherIconLabel3, -68 );
lv_obj_set_y( ui_WeatherIconLabel3, 56 );
lv_obj_set_align( ui_WeatherIconLabel3, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherIconLabel3,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherIconLabel3,"Sunny Cloudy");
lv_obj_set_style_text_font(ui_WeatherIconLabel3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureLabel3 = lv_label_create(ui_Block3);
lv_obj_set_width( ui_TemperatureLabel3, 95);
lv_obj_set_height( ui_TemperatureLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureLabel3, 59 );
lv_obj_set_y( ui_TemperatureLabel3, -52 );
lv_obj_set_align( ui_TemperatureLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureLabel3,"TemperatureRange");

ui_Temperature3 = lv_label_create(ui_Block3);
lv_obj_set_width( ui_Temperature3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature3, 62 );
lv_obj_set_y( ui_Temperature3, -11 );
lv_obj_set_align( ui_Temperature3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature3,"17~33°C");
lv_obj_set_style_text_font(ui_Temperature3, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Precipitation3 = lv_label_create(ui_Block3);
lv_obj_set_width( ui_Precipitation3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Precipitation3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Precipitation3, 62 );
lv_obj_set_y( ui_Precipitation3, 51 );
lv_obj_set_align( ui_Precipitation3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Precipitation3,"100%");
lv_obj_set_style_text_font(ui_Precipitation3, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrecipitationLabel3 = lv_label_create(ui_Block3);
lv_obj_set_width( ui_PrecipitationLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrecipitationLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrecipitationLabel3, 59 );
lv_obj_set_y( ui_PrecipitationLabel3, 20 );
lv_obj_set_align( ui_PrecipitationLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrecipitationLabel3,"Precipitation");

ui_Block4 = lv_obj_create(ui_BackBlock);
lv_obj_set_width( ui_Block4, 264);
lv_obj_set_height( ui_Block4, 165);
lv_obj_set_x( ui_Block4, 820 );
lv_obj_set_y( ui_Block4, 0 );
lv_obj_set_align( ui_Block4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Block4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeatherLabel4 = lv_label_create(ui_Block4);
lv_obj_set_width( ui_WeatherLabel4, 134);
lv_obj_set_height( ui_WeatherLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherLabel4, -53 );
lv_obj_set_y( ui_WeatherLabel4, -60 );
lv_obj_set_align( ui_WeatherLabel4, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherLabel4,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherLabel4,"September, 27");

ui_WeatherIcon4 = lv_image_create(ui_Block4);
lv_image_set_src(ui_WeatherIcon4, &ui_img_sunny_s_cloudy_png);
lv_obj_set_width( ui_WeatherIcon4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherIcon4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherIcon4, -61 );
lv_obj_set_y( ui_WeatherIcon4, -6 );
lv_obj_set_align( ui_WeatherIcon4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherIcon4, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherIcon4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherIcon4,100);

ui_WeatherIconLabel4 = lv_label_create(ui_Block4);
lv_obj_set_width( ui_WeatherIconLabel4, 100);
lv_obj_set_height( ui_WeatherIconLabel4, 20);
lv_obj_set_x( ui_WeatherIconLabel4, -68 );
lv_obj_set_y( ui_WeatherIconLabel4, 56 );
lv_obj_set_align( ui_WeatherIconLabel4, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherIconLabel4,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherIconLabel4,"Sunny Cloudy");
lv_obj_set_style_text_font(ui_WeatherIconLabel4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureLabel4 = lv_label_create(ui_Block4);
lv_obj_set_width( ui_TemperatureLabel4, 95);
lv_obj_set_height( ui_TemperatureLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureLabel4, 59 );
lv_obj_set_y( ui_TemperatureLabel4, -52 );
lv_obj_set_align( ui_TemperatureLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureLabel4,"TemperatureRange");

ui_Temperature4 = lv_label_create(ui_Block4);
lv_obj_set_width( ui_Temperature4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature4, 62 );
lv_obj_set_y( ui_Temperature4, -11 );
lv_obj_set_align( ui_Temperature4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature4,"17~33°C");
lv_obj_set_style_text_font(ui_Temperature4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Precipitation4 = lv_label_create(ui_Block4);
lv_obj_set_width( ui_Precipitation4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Precipitation4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Precipitation4, 62 );
lv_obj_set_y( ui_Precipitation4, 51 );
lv_obj_set_align( ui_Precipitation4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Precipitation4,"100%");
lv_obj_set_style_text_font(ui_Precipitation4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrecipitationLabel4 = lv_label_create(ui_Block4);
lv_obj_set_width( ui_PrecipitationLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrecipitationLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrecipitationLabel4, 59 );
lv_obj_set_y( ui_PrecipitationLabel4, 20 );
lv_obj_set_align( ui_PrecipitationLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrecipitationLabel4,"Precipitation");

ui_Block5 = lv_obj_create(ui_BackBlock);
lv_obj_set_width( ui_Block5, 264);
lv_obj_set_height( ui_Block5, 165);
lv_obj_set_x( ui_Block5, 1100 );
lv_obj_set_y( ui_Block5, 0 );
lv_obj_set_align( ui_Block5, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Block5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeatherLabel5 = lv_label_create(ui_Block5);
lv_obj_set_width( ui_WeatherLabel5, 134);
lv_obj_set_height( ui_WeatherLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherLabel5, -53 );
lv_obj_set_y( ui_WeatherLabel5, -60 );
lv_obj_set_align( ui_WeatherLabel5, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherLabel5,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherLabel5,"September, 27");

ui_WeatherIcon5 = lv_image_create(ui_Block5);
lv_image_set_src(ui_WeatherIcon5, &ui_img_sunny_s_cloudy_png);
lv_obj_set_width( ui_WeatherIcon5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherIcon5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherIcon5, -61 );
lv_obj_set_y( ui_WeatherIcon5, -6 );
lv_obj_set_align( ui_WeatherIcon5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherIcon5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherIcon5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherIcon5,100);

ui_WeatherIconLabel5 = lv_label_create(ui_Block5);
lv_obj_set_width( ui_WeatherIconLabel5, 100);
lv_obj_set_height( ui_WeatherIconLabel5, 20);
lv_obj_set_x( ui_WeatherIconLabel5, -68 );
lv_obj_set_y( ui_WeatherIconLabel5, 56 );
lv_obj_set_align( ui_WeatherIconLabel5, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_WeatherIconLabel5,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_WeatherIconLabel5,"Sunny Cloudy");
lv_obj_set_style_text_font(ui_WeatherIconLabel5, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureLabel5 = lv_label_create(ui_Block5);
lv_obj_set_width( ui_TemperatureLabel5, 95);
lv_obj_set_height( ui_TemperatureLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureLabel5, 59 );
lv_obj_set_y( ui_TemperatureLabel5, -52 );
lv_obj_set_align( ui_TemperatureLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureLabel5,"TemperatureRange");

ui_Temperature5 = lv_label_create(ui_Block5);
lv_obj_set_width( ui_Temperature5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature5, 62 );
lv_obj_set_y( ui_Temperature5, -11 );
lv_obj_set_align( ui_Temperature5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature5,"17~33°C");
lv_obj_set_style_text_font(ui_Temperature5, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Precipitation5 = lv_label_create(ui_Block5);
lv_obj_set_width( ui_Precipitation5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Precipitation5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Precipitation5, 62 );
lv_obj_set_y( ui_Precipitation5, 51 );
lv_obj_set_align( ui_Precipitation5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Precipitation5,"100%");
lv_obj_set_style_text_font(ui_Precipitation5, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PrecipitationLabel5 = lv_label_create(ui_Block5);
lv_obj_set_width( ui_PrecipitationLabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PrecipitationLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PrecipitationLabel5, 59 );
lv_obj_set_y( ui_PrecipitationLabel5, 20 );
lv_obj_set_align( ui_PrecipitationLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_PrecipitationLabel5,"Precipitation");

ui_FromWeatherBackToMenu = lv_label_create(ui_WeatherForcastPage);
lv_obj_set_width( ui_FromWeatherBackToMenu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FromWeatherBackToMenu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FromWeatherBackToMenu, -130 );
lv_obj_set_y( ui_FromWeatherBackToMenu, -105 );
lv_obj_set_align( ui_FromWeatherBackToMenu, LV_ALIGN_CENTER );
lv_label_set_text(ui_FromWeatherBackToMenu,"< Back");
lv_obj_add_flag( ui_FromWeatherBackToMenu, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_FromWeatherBackToMenu, lv_color_hex(0x5FD3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FromWeatherBackToMenu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeatherBarLabel = lv_label_create(ui_WeatherForcastPage);
lv_obj_set_width( ui_WeatherBarLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherBarLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherBarLabel, 0 );
lv_obj_set_y( ui_WeatherBarLabel, -105 );
lv_obj_set_align( ui_WeatherBarLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeatherBarLabel,"Weather");

ui_WeatherRefreshIcon = lv_image_create(ui_WeatherForcastPage);
lv_image_set_src(ui_WeatherRefreshIcon, &ui_img_refresh_png);
lv_obj_set_width( ui_WeatherRefreshIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherRefreshIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherRefreshIcon, 141 );
lv_obj_set_y( ui_WeatherRefreshIcon, -104 );
lv_obj_set_align( ui_WeatherRefreshIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherRefreshIcon, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherRefreshIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherRefreshIcon,12);

ui_WeatherRefreshNotice = lv_obj_create(ui_WeatherForcastPage);
lv_obj_set_width( ui_WeatherRefreshNotice, 216);
lv_obj_set_height( ui_WeatherRefreshNotice, 87);
lv_obj_set_x( ui_WeatherRefreshNotice, 0 );
lv_obj_set_y( ui_WeatherRefreshNotice, -200 );
lv_obj_set_align( ui_WeatherRefreshNotice, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_WeatherRefreshNotice, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeatherRefreshNoticeSpinner = lv_spinner_create(ui_WeatherRefreshNotice);
//lv_spinner_set_anim_params(ui_WeatherRefreshNoticeSpinner, 1000, 90);
lv_obj_set_width( ui_WeatherRefreshNoticeSpinner, 52);
lv_obj_set_height( ui_WeatherRefreshNoticeSpinner, 50);
lv_obj_set_x( ui_WeatherRefreshNoticeSpinner, -62 );
lv_obj_set_y( ui_WeatherRefreshNoticeSpinner, 0 );
lv_obj_set_align( ui_WeatherRefreshNoticeSpinner, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_WeatherRefreshNoticeSpinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_WeatherRefreshNoticeLabel = lv_label_create(ui_WeatherRefreshNotice);
lv_obj_set_width( ui_WeatherRefreshNoticeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherRefreshNoticeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherRefreshNoticeLabel, 35 );
lv_obj_set_y( ui_WeatherRefreshNoticeLabel, 0 );
lv_obj_set_align( ui_WeatherRefreshNoticeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeatherRefreshNoticeLabel,"Refreshing...");

ui_WeatherRefreshAcceptIcon = lv_image_create(ui_WeatherRefreshNotice);
lv_image_set_src(ui_WeatherRefreshAcceptIcon, &ui_img_accept_png);
lv_obj_set_width( ui_WeatherRefreshAcceptIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherRefreshAcceptIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherRefreshAcceptIcon, -62 );
lv_obj_set_y( ui_WeatherRefreshAcceptIcon, 0 );
lv_obj_set_align( ui_WeatherRefreshAcceptIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherRefreshAcceptIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherRefreshAcceptIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherRefreshAcceptIcon,30);

ui_WeatherRefreshDeclineIcon = lv_image_create(ui_WeatherRefreshNotice);
lv_image_set_src(ui_WeatherRefreshDeclineIcon, &ui_img_decline_png);
lv_obj_set_width( ui_WeatherRefreshDeclineIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeatherRefreshDeclineIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WeatherRefreshDeclineIcon, -62 );
lv_obj_set_y( ui_WeatherRefreshDeclineIcon, 0 );
lv_obj_set_align( ui_WeatherRefreshDeclineIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeatherRefreshDeclineIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_WeatherRefreshDeclineIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_WeatherRefreshDeclineIcon,42);

lv_obj_add_event_cb(ui_FromWeatherBackToMenu, ui_event_FromWeatherBackToMenu, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WeatherRefreshIcon, ui_event_WeatherRefreshIcon, LV_EVENT_ALL, NULL);

}
